<?xml version="1.0" encoding="utf-8"?>
<!-- <!DOCTYPE branch SYSTEM "branch.dtd"> -->
<!DOCTYPE branch [

<!ELEMENT branch (item+)>
<!ELEMENT item (address, contact, openingHours)>
<!ELEMENT openingHours (weekday, weekend)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT weekday (#PCDATA)>
<!ELEMENT weekend (#PCDATA)>

]>
<branch>
  <item>
    <address>76 Devonshire St, Surry Hills NSW</address>
    <map>https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3312.1438197215793!2d151.20556251509447!3d-33.88594968065153!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6b12ae21aea44cd5%3A0xcf2d54666d7cca73!2s76%20Devonshire%20St%2C%20Surry%20Hills%20NSW%202010!5e0!3m2!1sen!2sau!4v1635092152224!5m2!1sen!2sau</map>
    <contact>02 9211 1234</contact>
    <openingHours>
      <weekday>Mon - Fri: 6:00 to 14:30</weekday>
      <weekend>Sat-Sun: 7:00 to 15:00</weekend>
    </openingHours>
  </item>
</branch>
